version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - database
            - redis
        volumes: 
            - .:/app
            - gem_cache:/usr/local/bundle/gems
            - node_modules:/app/node_modules
        tty: true
        env_file: .env
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        environment:
            RAILS_ENV: development
        ports:
            - "3000:3000"
    database:
        image: "postgres:12.1"
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
    redis:
        image: redis:latest
    sidekiq:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - app
            - database
            - redis
        volumes:
            - .:/app
            - gem_cache:/usr/local/bundle/gems
            - node_modules:/app/node_modules
        tty: true
        env_file: .env
        environment:
            RAILS_ENV: development
            entrypoint: ./entrypoints/sidekiq-entrypoint.sh
volumes:
    gem_cache:
    db_data:
    node_modules:
