defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: database
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *defaults
  database: triage_development

test:
  <<: *defaults
  database: triage_test

production:
  <<: *defaults
  database: triage_production

